// 附魔交易所 状态定义
package com.example.addon.librarian;

public enum AutoLibrarianState {
    IDLE,
    START,
    SEARCH_VILLAGER,
    SELECT_TARGET_VILLAGER,
    MOVE_TO_VILLAGER,
    FIND_LECTERN_POSITION,
    MOVE_TO_STAND_POSITION,
    BREAK_OBSTACLE,
    PLACE_LECTERN,
    WAIT_PROFESSION,
    OPEN_TRADE,
    WAIT_TRADE_SCREEN,
    READ_TRADES,
    CHECK_ENCHANTMENT,
    RESET,
    BREAK_LECTERN,
    WAIT_UNEMPLOYED,
    SUCCESS_FOUND,
    TRADE_PROCESS,
    SELECT_TRADE,
    WAIT_TRADE_SYNC,
    TAKE_TRADE_OUTPUT,
    VERIFY_PURCHASE,
    COMPLETE_TARGET,
    END_VILLAGER_CYCLE,
    FINISH,
    ERROR
}
