package com.example.addon.modules;

import com.example.addon.core.AddonTemplate;
import com.example.addon.core.YiyiaddonModule;
import meteordevelopment.meteorclient.gui.GuiTheme;
import meteordevelopment.meteorclient.gui.widgets.WWidget;

public final class BaritoneCommandGuideModule extends YiyiaddonModule {
    public BaritoneCommandGuideModule() {
        super(AddonTemplate.CATEGORY, "Baritone指令说明", "打开后查看 Baritone 常用指令、参数格式和使用示例。");
        this.toggle(); // 默认开启
    }

    @Override
    public WWidget getWidget(GuiTheme theme) {
        return buildInfoWidget(theme,
            new String[]{ "§lBaritone 指令完全指南（超详细版）" },
            new String[]{
                "§e§l▌ 什么是 Baritone？",
                "§f  Baritone 是一个自动寻路机器人，可以帮你：",
                "§f  · 自动走到指定坐标",
                "§f  · 自动挖矿（钻石、铁矿等）",
                "§f  · 自动建造（按照原理图）",
                "§f  · 自动跟随玩家或实体",
                "§f  · 自动探索未知区域"
            },
            new String[]{
                "§a§l▌ 基础知识",
                "§f  · 所有指令都要加前缀 §e#§f，例如 §e#goto 100 64 200",
                "§f  · 坐标可以用相对值 §e~§f，例如 §e#goto ~10 ~ ~-5§f（往前 10 格）",
                "§f  · 不知道怎么用？输入 §e#help§f 查看命令列表",
                "§f  · 想停下来？输入 §e#cancel§f 立即停止当前任务",
                "§f  · 不小心走错了？输入 §e#cancel§f 然后重新输指令"
            },
            new String[]{
                "§b§l▌ 功能 1：自动走路",
                "§f  §e#goto 100 64 200§f - 走到坐标 X=100, Y=64, Z=200",
                "§f    · 会自动找路，绕过障碍物",
                "§f    · 会自动挖掘挡路的方块",
                "§f    · 会自动搭桥过河",
                "§f",
                "§f  §e#goto ~10 ~ ~§f - 往你看的方向走 10 格",
                "§f    · §e~§f 表示相对坐标",
                "§f    · §e~10§f = 当前坐标 + 10",
                "§f    · §e~-10§f = 当前坐标 - 10",
                "§f",
                "§f  §e#goto diamond_ore§f - 走到最近的钻石矿",
                "§f    · 会搜索附近的钻石矿",
                "§f    · 找到后自动走过去",
                "§f    · 如果没找到会提示你",
                "§f",
                "§f  §e#surface§f - 从地下回到地面",
                "§f    · 在矿洞迷路了就用这个",
                "§f    · 会自动找最短路线上去",
                "§f",
                "§f  §e#come§f - 走到你的摄像机位置",
                "§f    · 适合创造模式飞到高空后让角色过来"
            },
            new String[]{
                "§d§l▌ 功能 2：自动挖矿",
                "§f  §e#mine diamond_ore§f - 自动挖钻石",
                "§f    · 会搜索附近的钻石矿",
                "§f    · 自动走过去挖掉",
                "§f    · 挖完继续找下一个",
                "§f    · 输入 §e#cancel§f 停止",
                "§f",
                "§f  §e#mine iron_ore§f - 自动挖铁矿",
                "§f  §e#mine coal_ore§f - 自动挖煤矿",
                "§f  §e#mine redstone_ore§f - 自动挖红石",
                "§f  §e#mine ancient_debris§f - 自动挖远古残骸（下界）",
                "§f",
                "§f  §e#find diamond_ore§f - 只找不挖",
                "§f    · 会在聊天栏显示坐标",
                "§f    · 不会自动走过去",
                "§f",
                "§f  §e#explore§f - 自动探索地图",
                "§f    · 会往没去过的地方走",
                "§f    · 适合找村庄、遗迹等",
                "§f",
                "§f  §e#farm§f - 自动收割农作物",
                "§f    · 会收割成熟的小麦、土豆、胡萝卜",
                "§f    · 收割后自动重新种植",
                "§f",
                "§f  §e#tunnel 3 3 100§f - 挖一条 3x3 隧道，长度 100 格",
                "§f    · 按你面对的方向挖",
                "§f    · 适合挖矿道"
            },
            new String[]{
                "§6§l▌ 功能 3：自动建造",
                "§f  §e#build house.schematic§f - 按原理图建造房子",
                "§f    · 需要先把 .schematic 文件放到游戏目录",
                "§f    · 背包里要有足够的材料",
                "§f    · 会自动放置方块",
                "§f",
                "§f  §e#litematica§f - 建造 Litematica 投影",
                "§f    · 需要先用 Litematica Mod 加载原理图",
                "§f    · 然后用这个指令开始自动建造",
                "§f",
                "§f  §e#sel pos1§f 和 §e#sel pos2§f - 选区",
                "§f    · 先输入 §e#sel pos1§f，走到第一个角",
                "§f    · 再输入 §e#sel pos2§f，走到对角",
                "§f    · 就选好了一个立方体区域",
                "§f",
                "§f  §e#sel set stone§f - 用石头填满选区",
                "§f    · 先用上面的方法选区",
                "§f    · 然后用这个指令填充",
                "§f",
                "§f  §e#sel walls§f - 只建造选区的四面墙",
                "§f  §e#sel clear§f - 清空选区",
                "§f  §e#sel undo§f - 撤销上一步"
            },
            new String[]{
                "§c§l▌ 功能 4：保存路径点",
                "§f  §e#sethome§f - 在当前位置设置家",
                "§f    · 只需要输入一次",
                "§f    · 以后可以用 §e#home§f 回家",
                "§f",
                "§f  §e#home§f - 自动回家",
                "§f    · 会自动走到你设置的家",
                "§f    · 前提是你用过 §e#sethome",
                "§f",
                "§f  §e#wp save base 我的基地§f - 保存一个路径点",
                "§f    · §ebase§f 是标签（ID）",
                "§f    · §e我的基地§f 是名字（可以用中文）",
                "§f",
                "§f  §e#wp list§f - 查看所有路径点",
                "§f    · 会列出你保存的所有路径点",
                "§f",
                "§f  §e#wp goto base§f - 走到路径点",
                "§f    · 会自动走到标签为 base 的路径点",
                "§f",
                "§f  §e#wp delete base§f - 删除路径点",
                "§f    · 删除标签为 base 的路径点"
            },
            new String[]{
                "§5§l▌ 功能 5：跟随玩家",
                "§f  §e#follow player Steve§f - 跟随名叫 Steve 的玩家",
                "§f    · 会一直跟着他走",
                "§f    · 保持一定距离",
                "§f    · 输入 §e#cancel§f 停止跟随",
                "§f",
                "§f  §e#follow players§f - 跟随所有玩家",
                "§f    · 会跟着最近的玩家走",
                "§f",
                "§f  §e#follow entities§f - 跟随实体",
                "§f    · 可以跟随动物、怪物等",
                "§f  §e#follow horse§f - 跟随最近的马",
                "§f  §e#follow skeleton§f - 跟随最近的骷髅",
                "§f",
                "§f  §e#pause§f - 暂停当前任务",
                "§f    · 暂时停下，但不取消任务",
                "§f  §e#resume§f - 继续任务",
                "§f    · 从暂停的地方继续",
                "§f",
                "§f  §e#elytra§f - 用鞘翅飞到目标",
                "§f    · 需要穿鞘翅",
                "§f    · 需要有烟花火箭",
                "§f    · 会自动起飞并飞到目标"
            },
            new String[]{
                "§9§l▌ 高级功能",
                "§f  §e#set§f - 查看所有设置",
                "§f    · 会列出很多设置项",
                "§f    · 例如速度、路径查找算法等",
                "§f",
                "§f  §e#set allowBreak true§f - 允许挖方块",
                "§f  §e#set allowPlace true§f - 允许放方块",
                "§f  §e#set allowSprint true§f - 允许疾跑",
                "§f    · 这些是常用设置",
                "§f",
                "§f  §e#set reset all§f - 恢复默认设置",
                "§f    · 如果改乱了就用这个",
                "§f    · 会把所有设置改回默认值",
                "§f",
                "§f  §e#eta§f - 查看预计到达时间",
                "§f    · 会显示还要多久到目标",
                "§f",
                "§f  §e#version§f - 查看 Baritone 版本",
                "§f    · 显示你用的 Baritone 版本号"
            },
            new String[]{
                "§e§l▌ 常见问题",
                "§f",
                "§f  §c问：输入指令没反应？",
                "§f  §a答：检查是否加了前缀 §e#§a，例如 §e#goto§a 不是 §egoto",
                "§f",
                "§f  §c问：说找不到钻石矿？",
                "§f  §a答：需要先走到附近让 Baritone 缓存地图",
                "§f     或者用 §e#explore§a 先探索一下",
                "§f",
                "§f  §c问：卡住不动了？",
                "§f  §a答：输入 §e#cancel§a 停止，然后重新输指令",
                "§f",
                "§f  §c问：建造时说缺材料？",
                "§f  §a答：去补充材料，然后输入 §e#resume§a 继续",
                "§f",
                "§f  §c问：走得太慢？",
                "§f  §a答：输入 §e#set allowSprint true§a 允许疾跑",
                "§f",
                "§f  §c问：不挖脚下的方块？",
                "§f  §a答：输入 §e#set allowBreak true§a 允许挖方块",
                "§f",
                "§f  §c问：怎么停止？",
                "§f  §a答：输入 §e#cancel§a 立即停止当前所有任务",
                "§f",
                "§f  §7注意：本模块只显示说明，不会自动执行任何指令"
            }
        );
    }
}
